eureka:
    client:
        service-url:
            defaultZone: http://192.168.40.132:10086/eureka
feign:
    hystrix:
        enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    strategy: SEMAPHORE
logging:
    level:
        cn:
            project:
                mapper: debug
mybatis:
    type-aliases-package: cn.project.entity
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
    type-aliases-package: cn.project.entity
spring:
    application:
        name: clinicPrescription
    datasource:
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.40.132:3306/prescriptiondata?serverTimezone=UTC
        username: root
    rabbitmq:
        addresses: amqp://192.168.40.132:5672
        password: 123456
        username: admin
    zipkin:
      base-url: http://192.168.40.132:9411/